# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# install build dependencies
RUN apk add --no-cache python3 make g++ git

# copy sources
COPY package.json tsconfig.json .
COPY batchdata_mcp_server.ts .

# install production deps and dev deps
RUN npm install --ignore-scripts

# patch dotenv import
RUN sed -i 's@import dotenv from "dotenv"@import * as dotenv from "dotenv"@' batchdata_mcp_server.ts

# compile
RUN npm install typescript @types/node --no-save \
    && npm run build

# prune dev deps
RUN npm prune --production \
    && apk del python3 make g++ git

# runtime image
FROM node:lts-alpine
WORKDIR /app

# copy runtime artifacts
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/batchdata_mcp_server.js ./batchdata_mcp_server.js

ENTRYPOINT ["node", "batchdata_mcp_server.js"]
